INSERT INTO defaultdb.users (id, first_name, last_name, age, email, username, password) VALUES (1, 'Paul', 'Harrohide', 20, 'paulh@yahoo.fr''ph', 'aaa');
INSERT INTO defaultdb.users (id, first_name, last_name, age, email, username, password) VALUES (2, 'Harry', 'Covert', 25, 'harrycov@yahoo.fr', 'harrc', 'bbb');
INSERT INTO defaultdb.users (id, first_name, last_name, age, email, username, password) VALUES (3, 'Alain', 'Posteur', 26, 'alainposteur@gmail.com', 'apost', 'ccc');
INSERT INTO defaultdb.users (id, first_name, last_name, age, email, username, password) VALUES (4, 'Elvire', 'Debord', 28, 'elvired@yahoo.com', 'elvireD', 'ddd');
INSERT INTO defaultdb.users (id, first_name, last_name, age, email, username, password) VALUES (5, 'Laurent', 'Barre', 41, 'laurentb@gmail.com', 'LaurentB', 'eee');
INSERT INTO defaultdb.users (id, first_name, last_name, age, email, username, password) VALUES (6, 'Homer', 'Cipourtoux', 28, 'homerc@gmail.com', 'HomerC', 'fff');
INSERT INTO defaultdb.users (id, first_name, last_name, age, email, username, password) VALUES (7, 'Gaston', 'Laplouz', 30, 'gastonlz@gmail.com', 'GastonL', 'ggg');
INSERT INTO defaultdb.users (id, first_name, last_name, age, email, username, password) VALUES (8, 'Gisèle', 'Detable', 42, 'giseled@yahoo.fr', 'GiseleD', 'hhh');
INSERT INTO defaultdb.users (id, first_name, last_name, age, email, username, password) VALUES (9, 'Thomas', 'Ouaque', 18, 'thomaso@epfedu.fr', 'ThomasO', 'iii');
INSERT INTO defaultdb.users (id, first_name, last_name, age, email, username, password) VALUES (10, 'Sacha', 'Telfrize', 23, 'sachat@epfedu.fr', 'SachaT', 'jjj');
